language: ruby
rvm:
  - 1.9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rackup -D ./test/config.ru
  - sleep 2

script: phantomjs ./vendor/run-qunit.coffee "http://localhost:9292/"

notifications:
  disabled: true
